[package]
name = "async_graphql_telemetry_extension"
version = "0.1.0"
authors = ["Naaman <naaman.the.dev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-graphql = "2.4.11"
async-trait = "0.1.42"
async-graphql-parser = "2.4.6"
tracing = "0.1.22"
serde = "1.0.119"
chrono = "0.4.19"
lazy_static = "1.4.0"
opentelemetry = { version = "0.11.2", features = ["metrics"] }

[dev-dependencies]
tokio = { version = "1.0.2", features = ["full"] }
